language: python
python:
  - "3.11"  # Use a stable Python version
dist: focal
os: linux

env:
  - BASE_PATH="backend/nightwalkers" FRONTEND_PATH="frontend"

before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable  # Enables newer GDAL versions
  - sudo apt-get update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev
  - gdalinfo --version  # Check if it installed correctly

cache:
  directories:
    - ~/.cache/pip
    - ~/.npm  # Cache global npm packages
    - ~/.cache/npm  # Cache npm cache
    - frontend/node_modules  # Cache project dependencies
    - frontend/build
    - frontend/.next/cache
  npm: true # Add explicit npm caching
  pip: true # Add explicit pip caching

# Install dependencies
install:
# Install GDAL via pip (ensure it matches the system-installed version)
  # - pip install GDAL==3.4.0 --no-cache-dir  # Specify a newer version of GDAL
  - pip install --no-cache-dir GDAL==3.6.4  # Explicitly install a compatible GDAL version
  - pip install -r backend/nightwalkers/requirements.txt
  - pip install black flake8 coverage coveralls

# Install Node.js and frontend dependencies
  - nvm install 22.9  # Install Node.js 22 (or the version your Next.js app requires)
  - npm install -g npm@10.8  # Update npm to the latest version
  - cd $FRONTEND_PATH && npm install && cd ..  # Install frontend dependencies

# Make the script executable
before_script:
  - chmod +x deploy.sh
  - chmod +x deploy-to-production.sh
  - chmod +x deploy-to-develop.sh
  - chmod +x deploy-to-netlify.sh
  # - psql -U postgres -c "DROP DATABASE IF EXISTS test_[secure];"  # For PostgreSQL

# Run checks and tests
script:
  - pwd

  - black --check backend/nightwalkers/
  - flake8 backend/nightwalkers/

  - coverage run --source=$BASE_PATH $BASE_PATH/manage.py test $BASE_PATH --keepdb
  - coverage report  # Print coverage report
  - coverage xml  # Generate coverage XML for coveralls

  # Frontend build
  - cd $FRONTEND_PATH && npm run build && cd ..  # Build the Next.js app

# Report coverage to coveralls
after_success:
  - coveralls --service=travis-pro

# Deploy to AWS Elastic Beanstalk upon successful tests for the main and develop branches
deploy:
  provider: script
  script: ./deploy.sh
  cleanup: false
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(main|develop)$
# Notifications (optional)
notifications:
  email:
    on_success: never
    on_failure: always



