# Generated by Django 5.1.6 on 2025-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedroute",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
