# Generated by Django 5.1.6 on 2025-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_comment_parent_comment_commentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="like_type",
            field=models.CharField(default="Like", max_length=10, null=True),
        ),
    ]
